import Navbar from '@/components/Navbar'
import Providers from '@/components/Providers'
import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import 'react-loading-skeleton/dist/skeleton.css'
import 'simplebar-react/dist/simplebar.min.css'
import { Toaster } from 'sonner'
import './globals.css'
import { getKindeServerSession } from '@kinde-oss/kinde-auth-nextjs/server'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Quill',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const { getUser } = getKindeServerSession()
  const user = await getUser()

  return (
    <html lang='en'>
      <Providers>
        <body
          className={cn(
            inter.className,
            'min-h-screen font-sans antialiased grainy'
          )}
        >
          <Navbar user={null} />
          {children}
          <Toaster />
        </body>
      </Providers>
    </html>
  )
}
